### ISSUE TITLE
[Build Bots] Build Test for Pull Request.

### ISSUE THREAD

**Issue by hyowon** [Samsung/Castanets#133]
[Build Bots] Build Test for Pull Request.

**Comment by Chikdolman** [comment]
Note: If /base gets modified, for instance (https://github.com/Samsung/Castanets/pull/135), maximum build time for the Travis is not enough to build the binary even if we execute the partial build. 
Therefore, new CI tool is required for auto-build. Now, I am trying to get in touch with Circle CI admin team for support.

**Comment by Chikdolman** [comment]
Status update for applying Circle CI

 
Stella Lok (CircleCI) 

Jul 8, 01:41 PDT 

Hi Seikwon,
Thanks for the update. Could you try recreating the image by running docker build with the --no-cache argument before pushing it?
Stella Lok
 Senior Support Engineer @ CircleCI

 
seikwon.kim 

Jul 8, 01:18 PDT 

Hi Stella
Thanks for supporting.
I tried to specify the image as - image: seikwon/castanets_69_base@sha256:9d00afa02a2633206715a7bcd7a2216bf0951bede563184318b6a5b3f31eaba7 in .config.yml
However, no luck.
I still get the following error
Original error: failed to register layer: Error processing tar file(exit status 1): Container ID 376730 cannot be mapped to a host ID

Seikwon Kim

--------- Original Message ---------

Sender : CircleCI <support@circleci.zendesk.com>
Date : 2019-07-08 17:01 (GMT+9)
Title : [CircleCI] Re: attach CircleCI tool to Github

 
  
Stella Lok (CircleCI) 
Jul 8, 01:01 PDT 
Hi Seikwon,
Could you try specifying the image in the config.yml as seikwon/castanets_69_base:latest@sha256:<HASH> to be sure that the the latest image that you pushed, which contains the fix for the uid issue, is being used? (For more details on how to specify an image with a SHA digest, see: https://support.circleci.com/hc/en-us/articles/115015742147-Did-something-change-in-the-CircleCI-Docker-Images-)
Stella Lok
 Senior Support Engineer @ CircleCI
  
seikwon.kim 
Jul 8, 00:21 PDT 
Sorry the reply was a bit messy, so sending you again.
Hello Eugene,
Thanks for your help.
I tried following command you described before reaching you out, since it was described in the CircleCI helpdesk page.
find / \( -uid 376730 \)  -ls 2>/dev/null
I had a problem in the previous docker image and fixed the uid issue in the previous docker as described in the helpdesk page, then uploaded fixed image on the dockerhub.
However I still see the identical issue with the fixed image.
When I do the 'find', I do not see any uid with 376730 anymore in the seikwon/castanets_69_base:190708_1342 image.
I wonder if there is any issue that might cause the problem
 
Regards

Seikwon Kim


--------- Original Message ---------

Sender : CircleCI <support@circleci.zendesk.com>
Date : 2019-07-08 15:59 (GMT+9)
Title : [CircleCI] Re: attach CircleCI tool to Github

  
seikwon.kim 
Jul 8, 00:20 PDT 


Hello Eugene,
Thanks for your help.
I tried following command you described before reaching you out, since it was described in the CircleCI helpdesk page.
find / \( -uid 376730 \)  -ls 2>/dev/null


--------- Original Message ---------
I had a problem in the previous docker image and fixed the uid issue in the previous docker as described in the helpdesk page, then uploaded fixed image on the dockerhub.
However I still see the identical issue with the fixed image.
When I do the 'find', I do not see any uid with 376730 anymore in the seikwon/castanets_69_base:190708_1342 image.
I wonder if there is any issue that might cause the problem

Regards

Seikwon Kim

 
Sender : CircleCI <support@circleci.zendesk.com>
Date : 2019-07-08 15:59 (GMT+9)
Title : [CircleCI] Re: attach CircleCI tool to Github
 
  
Eugene Choe (CircleCI) 
Jul 7, 23:59 PDT 

Hi Seikwon,
Thank you for reaching out! Could you try running the Docker image that you have in your config.yml (seikwon/castanets_69_base:190708_1342) locally and running the following command to see what the process is?
find / \( -uid 376730 \)  -ls 2>/dev/null
Most likely we'll need to make a change to your base Docker image depending on the result.
Thanks,
Eugene Choe
 CircleCI Solutions Engineer

 
  
Hiroki Kondo (CircleCI) 
Jul 7, 22:38 PDT 
Hello Seikwon,
Thanks for reaching out to us. Our team will respond to your question shortly.
 Regards,
 Hiroki

ーーーーーーーーーーーーーーーーーーーーーーーーーー

Dear whom this may concern,

I'm trying to attach CircleCI tool to Github(https://github.com/Chikdolman/Castanets/blob/travis/.circleci/config.yml).
 However, the current config file gives me an error as follows, which I don't contain any UID 376730 in my docker(seikwon/castanets_69_base:190708_1342).
 Am I missing something? or is there a solution to the following problem? Thanks in advance!

CircleCI was unable to start the container because of a userns remapping failure in Docker.

This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.

Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
 Original error: CircleCI was unable to start the container because of a userns remapping failure in Docker.

This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.

Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
 Original error: failed to register layer: Error processing tar file(exit status 1): Container ID 376730 cannot be mapped to a host ID

**Comment by Chikdolman** [comment]
Unknown high-UID error has been fixed.
However, the memory size issue occurred while building the Castanets.
Thus, trying to increase VM size from medium(default) to xlarge.


Stella Lok (CircleCI) 
Jul 10, 00:23 PDT 

Hi Seikwon,
We'll be happy to help you with this. An account representative who can advise on increasing the resource size will be in touch soon.
Stella Lok
 Senior Support Engineer @ CircleCI

   
seikwon.kim 
Jul 10, 00:15 PDT 

Hi CircleCI team,
I am trying to attach circleCI. However, I get the following error while building the code.

Exited with code 137Hint: 
Exit code 137 typically means the process is killed because it was running out of memory
Hint: Check if you can optimize the memory usage in your appHint: Max memory usage of this container is 4283551744 according to /sys/fs/cgroup/memory/memory.max_usage_in_bytes

I searched on the web to increase the memory size of the node, and I found that 
"resource_class" can be used in the yml.
However when I try resource_class: xlarge, I get following msg.

Resource class xlarge for docker is not available for your project. Default class medium will be used. Please contact your CSM person or our support team to whitelist your project.

I would like to use xlarge for following two repos, one for development and the other for original PR.
Would it be possible to increase the resource size for following two repos?
1. https://github.com/Samsung/Castanets
2. https://github.com/Chikdolman/Castanets

Best regards and thanks for your support!

Seikwon Kim
