### ISSUE TITLE
[DCHECK] ChildProcessLauncherHelper::GetFilesToMap()

### ISSUE THREAD

**Issue by hyowon** [Samsung/Castanets#174]
Sub-task of #128

[25528:25565:0802/080850.573201:FATAL:optional.h(583)] Check failed: storage_.is_populated_. 
#0 0x7f6e87c55e5c base::debug::StackTrace::StackTrace()
#1 0x7f6e87b7e23b logging::LogMessage::~LogMessage()
#2 0x7f6e84ff3368 content::internal::ChildProcessLauncherHelper::GetFilesToMap()
#3 0x7f6e84ff1d60 content::internal::ChildProcessLauncherHelper::LaunchOnLauncherThread()
#4 0x7f6e84b8b70b _ZN4base8internal7InvokerINS0_9BindStateIMN7content28ServiceManagerConnectionImpl15IOThreadContextEFvvEJ13scoped_refptrIS5_EEEEFvvEE7RunOnceEPNS0_13BindStateBaseE
#5 0x7f6e87b5ee5d base::debug::TaskAnnotator::RunTask()
#6 0x7f6e87c100b9 base::internal::TaskTracker::RunOrSkipTask()
#7 0x7f6e87c6a73b base::internal::TaskTrackerPosix::RunOrSkipTask()
#8 0x7f6e87c0f23c base::internal::TaskTracker::RunAndPopNextTask()
#9 0x7f6e87c04dcd base::internal::SchedulerWorker::RunWorker()
#10 0x7f6e87c04bc4 base::internal::SchedulerWorker::RunDedicatedWorker()
#11 0x7f6e87c6b05f base::(anonymous namespace)::ThreadFunc()
#12 0x7f6e7c8ee6ba start_thread
#13 0x7f6e7a86941d clone

**Comment by Tanvir-rizvi** [comment]
Recently I went to dig this bug a little and here is the initial analysis. 
Since we are creating mojo_named_channel for distributed channels from ChildProcessLauncherHelper::StartLaunchOnClientThread, therefore mojo_channel_ is not getting allocated( emplace not  happening). Hence this DCHECK is failing while accessing remote_endpoint() for unallocated mojo_channel_ from GetFilesToMap().

**Comment by hyowon** [comment]
https://github.com/Samsung/Castanets/pull/189
